spring:
  cloud:
    gateway:
      routes:
      - id: luohz
        uri: https://www.baidu.com/
        predicates:
        - Path=/luobaidu
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
